#### Project-6 Maintenance prediction
Prepared for: ExxpertSCM Thoughtware Training Pvt Ltd.


Guided by:  Mr. Pattabhi Raman


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import io


In [ ]:
columns=["id","cycle","op1","op2","op3","sensor1","sensor2","sensor3","sensor4","sensor5","sensor6","sensor7","sensor8",
         "sensor9","sensor10","sensor11","sensor12","sensor13","sensor14","sensor15","sensor16","sensor17","sensor18","sensor19"
         ,"sensor20","sensor21","sensor22","sensor23"]


In [ ]:
train=pd.read_csv("train_FD003.csv",names = columns)
test=pd.read_csv("test_FD003.csv",names=columns)
test_results=pd.read_csv("RUL_FD003.csv",header=None)

In [ ]:
train.head()


id  cycle     op1     op2  op3  sensor1  sensor2  sensor3  sensor4  \
0   1      1 -0.0005  0.0004  100   518.67   642.36  1583.23  1396.84   
1   1      2  0.0008 -0.0003  100   518.67   642.50  1584.69  1396.89   
2   1      3 -0.0014 -0.0002  100   518.67   642.18  1582.35  1405.61   
3   1      4 -0.0020  0.0001  100   518.67   642.92  1585.61  1392.27   
4   1      5  0.0016  0.0000  100   518.67   641.68  1588.63  1397.65   

   sensor5  ...  sensor14  sensor15  sensor16  sensor17  sensor18  sensor19  \
0    14.62  ...   8145.32    8.4246      0.03       391      2388       100   
1    14.62  ...   8152.85    8.4403      0.03       392      2388       100   
2    14.62  ...   8150.17    8.3901      0.03       391      2388       100   
3    14.62  ...   8146.56    8.3878      0.03       392      2388       100   
4    14.62  ...   8147.80    8.3869      0.03       392      2388       100   

   sensor20  sensor21  sensor22  sensor23  
0     39.11   23.3537       NaN       NaN  
1     38.99   23.4491       NaN       NaN  
2     38.85   23.3669       NaN       NaN  
3     38.96   23.2951       NaN       NaN  
4     39.14   23.4583       NaN       NaN  

[5 rows x 28 columns]

In [ ]:
train.shape

(24720, 28)

In [ ]:
train.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24720 entries, 0 to 24719
Data columns (total 28 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   id        24720 non-null  int64  
 1   cycle     24720 non-null  int64  
 2   op1       24720 non-null  float64
 3   op2       24720 non-null  float64
 4   op3       24720 non-null  int64  
 5   sensor1   24720 non-null  float64
 6   sensor2   24720 non-null  float64
 7   sensor3   24720 non-null  float64
 8   sensor4   24720 non-null  float64
 9   sensor5   24720 non-null  float64
 10  sensor6   24720 non-null  float64
 11  sensor7   24720 non-null  float64
 12  sensor8   24720 non-null  float64
 13  sensor9   24720 non-null  float64
 14  sensor10  24720 non-null  float64
 15  sensor11  24720 non-null  float64
 16  sensor12  24720 non-null  float64
 17  sensor13  24720 non-null  float64
 18  sensor14  24720 non-null  float64
 19  sensor15  24720 non-null  float64
 20  sensor16  24720 non-null  fl

In [ ]:
train.isnull().sum()

id              0
cycle           0
op1             0
op2             0
op3             0
sensor1         0
sensor2         0
sensor3         0
sensor4         0
sensor5         0
sensor6         0
sensor7         0
sensor8         0
sensor9         0
sensor10        0
sensor11        0
sensor12        0
sensor13        0
sensor14        0
sensor15        0
sensor16        0
sensor17        0
sensor18        0
sensor19        0
sensor20        0
sensor21        0
sensor22    24720
sensor23    24720
dtype: int64

In [ ]:
train = train.drop(['sensor22','sensor23'], axis = 1)


In [ ]:
train = train.dropna(axis = 0,how ='any')
train.isnull().sum()

id          0
cycle       0
op1         0
op2         0
op3         0
sensor1     0
sensor2     0
sensor3     0
sensor4     0
sensor5     0
sensor6     0
sensor7     0
sensor8     0
sensor9     0
sensor10    0
sensor11    0
sensor12    0
sensor13    0
sensor14    0
sensor15    0
sensor16    0
sensor17    0
sensor18    0
sensor19    0
sensor20    0
sensor21    0
dtype: int64

In [ ]:
test_results.columns=["rul"]
test_results.head()

rul
0   44
1   51
2   27
3  120
4  101

In [ ]:
test_results['id']=test_results.index+1
test_results.head()


rul  id
0   44   1
1   51   2
2   27   3
3  120   4
4  101   5

In [ ]:
rul = pd.DataFrame(train.groupby('id')['cycle'].max()).reset_index()
rul.columns = ['id', 'max']
rul

id  max
0     1  259
1     2  253
2     3  222
3     4  272
4     5  213
..  ...  ...
95   96  491
96   97  275
97   98  307
98   99  145
99  100  152

[100 rows x 2 columns]

In [ ]:
test_results['rul_failed']=test_results['rul']+rul['max']
test_results


rul   id  rul_failed
0    44    1         303
1    51    2         304
2    27    3         249
3   120    4         392
4   101    5         314
..  ...  ...         ...
95  113   96         604
96  123   97         398
97   17   98         324
98    8   99         153
99   28  100         180

[100 rows x 3 columns]

In [ ]:
train=train.merge(test_results,on=['id'],how='left')
train

id  cycle     op1     op2  op3  sensor1  sensor2  sensor3  sensor4  \
0        1      1 -0.0005  0.0004  100   518.67   642.36  1583.23  1396.84   
1        1      2  0.0008 -0.0003  100   518.67   642.50  1584.69  1396.89   
2        1      3 -0.0014 -0.0002  100   518.67   642.18  1582.35  1405.61   
3        1      4 -0.0020  0.0001  100   518.67   642.92  1585.61  1392.27   
4        1      5  0.0016  0.0000  100   518.67   641.68  1588.63  1397.65   
...    ...    ...     ...     ...  ...      ...      ...      ...      ...   
24715  100    148 -0.0016 -0.0003  100   518.67   643.78  1596.01  1424.11   
24716  100    149  0.0034 -0.0003  100   518.67   643.29  1596.38  1429.14   
24717  100    150 -0.0016  0.0004  100   518.67   643.84  1604.53  1431.41   
24718  100    151 -0.0023  0.0004  100   518.67   643.94  1597.56  1426.57   
24719  100    152  0.0000  0.0003  100   518.67   643.64  1599.04  1436.06   

       sensor5  ...  sensor14  sensor15  sensor16  sensor17  sensor18  \
0        14.62  ...   8145.32    8.4246      0.03       391      2388   
1        14.62  ...   8152.85    8.4403      0.03       392      2388   
2        14.62  ...   8150.17    8.3901      0.03       391      2388   
3        14.62  ...   8146.56    8.3878      0.03       392      2388   
4        14.62  ...   8147.80    8.3869      0.03       392      2388   
...        ...  ...       ...       ...       ...       ...       ...   
24715    14.62  ...   8138.08    8.5036      0.03       394      2388   
24716    14.62  ...   8144.36    8.5174      0.03       395      2388   
24717    14.62  ...   8135.95    8.5223      0.03       396      2388   
24718    14.62  ...   8141.24    8.5148      0.03       395      2388   
24719    14.62  ...   8136.98    8.5150      0.03       396      2388   

       sensor19  sensor20  sensor21  rul  rul_failed  
0           100     39.11   23.3537   44         303  
1           100     38.99   23.4491   44         303  
2           100     38.85   23.3669   44         303  
3           100     38.96   23.2951   44         303  
4           100     39.14   23.4583   44         303  
...         ...       ...       ...  ...         ...  
24715       100     38.44   22.9631   28         180  
24716       100     38.50   22.9746   28         180  
24717       100     38.39   23.0682   28         180  
24718       100     38.31   23.0753   28         180  
24719       100     38.56   23.0847   28         180  

[24720 rows x 28 columns]

In [ ]:
train["RUL"]=train["rul_failed"]-train["cycle"]
train

id  cycle     op1     op2  op3  sensor1  sensor2  sensor3  sensor4  \
0        1      1 -0.0005  0.0004  100   518.67   642.36  1583.23  1396.84   
1        1      2  0.0008 -0.0003  100   518.67   642.50  1584.69  1396.89   
2        1      3 -0.0014 -0.0002  100   518.67   642.18  1582.35  1405.61   
3        1      4 -0.0020  0.0001  100   518.67   642.92  1585.61  1392.27   
4        1      5  0.0016  0.0000  100   518.67   641.68  1588.63  1397.65   
...    ...    ...     ...     ...  ...      ...      ...      ...      ...   
24715  100    148 -0.0016 -0.0003  100   518.67   643.78  1596.01  1424.11   
24716  100    149  0.0034 -0.0003  100   518.67   643.29  1596.38  1429.14   
24717  100    150 -0.0016  0.0004  100   518.67   643.84  1604.53  1431.41   
24718  100    151 -0.0023  0.0004  100   518.67   643.94  1597.56  1426.57   
24719  100    152  0.0000  0.0003  100   518.67   643.64  1599.04  1436.06   

       sensor5  ...  sensor15  sensor16  sensor17  sensor18  sensor19  \
0        14.62  ...    8.4246      0.03       391      2388       100   
1        14.62  ...    8.4403      0.03       392      2388       100   
2        14.62  ...    8.3901      0.03       391      2388       100   
3        14.62  ...    8.3878      0.03       392      2388       100   
4        14.62  ...    8.3869      0.03       392      2388       100   
...        ...  ...       ...       ...       ...       ...       ...   
24715    14.62  ...    8.5036      0.03       394      2388       100   
24716    14.62  ...    8.5174      0.03       395      2388       100   
24717    14.62  ...    8.5223      0.03       396      2388       100   
24718    14.62  ...    8.5148      0.03       395      2388       100   
24719    14.62  ...    8.5150      0.03       396      2388       100   

       sensor20  sensor21  rul  rul_failed  RUL  
0         39.11   23.3537   44         303  302  
1         38.99   23.4491   44         303  301  
2         38.85   23.3669   44         303  300  
3         38.96   23.2951   44         303  299  
4         39.14   23.4583   44         303  298  
...         ...       ...  ...         ...  ...  
24715     38.44   22.9631   28         180   32  
24716     38.50   22.9746   28         180   31  
24717     38.39   23.0682   28         180   30  
24718     38.31   23.0753   28         180   29  
24719     38.56   23.0847   28         180   28  

[24720 rows x 29 columns]

In [ ]:
df_train = train.drop(['rul'],axis = 1)

In [ ]:
df_train.head()


id  cycle     op1     op2  op3  sensor1  sensor2  sensor3  sensor4  \
0   1      1 -0.0005  0.0004  100   518.67   642.36  1583.23  1396.84   
1   1      2  0.0008 -0.0003  100   518.67   642.50  1584.69  1396.89   
2   1      3 -0.0014 -0.0002  100   518.67   642.18  1582.35  1405.61   
3   1      4 -0.0020  0.0001  100   518.67   642.92  1585.61  1392.27   
4   1      5  0.0016  0.0000  100   518.67   641.68  1588.63  1397.65   

   sensor5  ...  sensor14  sensor15  sensor16  sensor17  sensor18  sensor19  \
0    14.62  ...   8145.32    8.4246      0.03       391      2388       100   
1    14.62  ...   8152.85    8.4403      0.03       392      2388       100   
2    14.62  ...   8150.17    8.3901      0.03       391      2388       100   
3    14.62  ...   8146.56    8.3878      0.03       392      2388       100   
4    14.62  ...   8147.80    8.3869      0.03       392      2388       100   

   sensor20  sensor21  rul_failed  RUL  
0     39.11   23.3537         303  302  
1     38.99   23.4491         303  301  
2     38.85   23.3669         303  300  
3     38.96   23.2951         303  299  
4     39.14   23.4583         303  298  

[5 rows x 28 columns]

In [ ]:
df = df_train.copy()

In [ ]:
from sklearn.model_selection import train_test_split
X1=df.drop(["id","cycle","op3","sensor1","sensor5","sensor6","sensor10","sensor16","sensor18","sensor19","RUL"],axis=1)
y1=df['RUL']

In [ ]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X1,y1, test_size = 0.20, random_state = 42)


In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(Xtrain,ytrain)
train_pred1 = lr.predict(Xtrain)
test_pred1 = lr.predict(Xtest)

In [ ]:
from sklearn.metrics import mean_squared_error
rmse_train1 = mean_squared_error(ytrain,train_pred1,squared = False)
rmse_train1

58.81577076588761

In [ ]:
rmse_test1 = mean_squared_error(ytest,test_pred1,squared = False)
rmse_test1

58.93758483988377

In [ ]:
from sklearn.neural_network import MLPRegressor
mlp = MLPRegressor()
mlp.fit(Xtrain,ytrain)
train_pred2 = mlp.predict(Xtrain)
test_pred2= mlp.predict(Xtest)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [ ]:
rmse_train2 = mean_squared_error(ytrain,train_pred2,squared = False)
rmse_train2

68.14505187795352

In [ ]:
rmse_test2 = mean_squared_error(ytest,test_pred2,squared = False)
rmse_test2

67.26957199726654

In [ ]:
from sklearn.svm import SVR
svr = SVR()
svr.fit(Xtrain,ytrain)
train_pred3 = svr.predict(Xtrain)
test_pred3 = svr.predict(Xtest)

In [ ]:
rmse_train3 = mean_squared_error(ytrain,train_pred3,squared = False)
rmse_train3

105.71171058921794

In [ ]:
rmse_test3 = mean_squared_error(ytest,test_pred3,squared = False)
rmse_test3

105.35894807767347

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor(max_depth = 7)
rfr.fit(Xtrain,ytrain)
train_pred4 = rfr.predict(Xtrain)
test_pred4 = rfr.predict(Xtest)

In [ ]:
rmse_train4 = mean_squared_error(ytrain,train_pred4,squared = False)
rmse_train4

43.22402338153193

In [ ]:
rmse_test4 = mean_squared_error(ytest,test_pred4,squared = False)
rmse_test4

46.06663873384177

In [ ]:
df1 = pd.DataFrame({'actual':ytest,'linearreg':test_pred1,'mlp':test_pred2,'svm':test_pred3,'randomforest':test_pred4})
df1

actual   linearreg         mlp         svm  randomforest
2501      147  206.985173  240.217628  201.048313    143.575890
19936     204  242.883991  259.780907  199.964567    251.514902
4645      182  189.030714  241.024260  200.891368    152.452207
1661      330  363.327185  322.582953  201.662064    364.122857
9849      441  356.255776  317.702656  201.377052    388.590071
...       ...         ...         ...         ...           ...
11550     209  230.047922  258.516084  200.970521    190.221998
24325     114  163.811924  230.233707  199.374739    169.118301
11467     292  302.049388  316.354420  201.057391    300.928171
19415      70  138.999150  140.726864  198.291654     90.589660
18075     139  166.378687  183.864463  198.815511    145.746503

[4944 rows x 5 columns]

In [ ]:
test.head()

id  cycle     op1     op2  op3  sensor1  sensor2  sensor3  sensor4  \
0   1      1 -0.0017 -0.0004  100   518.67   641.94  1581.93  1396.93   
1   1      2  0.0006 -0.0002  100   518.67   642.02  1584.86  1398.90   
2   1      3  0.0014 -0.0003  100   518.67   641.68  1581.78  1391.92   
3   1      4  0.0027  0.0001  100   518.67   642.20  1584.53  1395.34   
4   1      5 -0.0001  0.0001  100   518.67   642.46  1589.03  1395.86   

   sensor5  ...  sensor14  sensor15  sensor16  sensor17  sensor18  sensor19  \
0    14.62  ...   8133.48    8.3760      0.03       391      2388       100   
1    14.62  ...   8137.44    8.4062      0.03       391      2388       100   
2    14.62  ...   8138.25    8.3553      0.03       391      2388       100   
3    14.62  ...   8137.07    8.3709      0.03       392      2388       100   
4    14.62  ...   8134.20    8.4146      0.03       391      2388       100   

   sensor20  sensor21  sensor22  sensor23  
0     39.07   23.4468       NaN       NaN  
1     39.04   23.4807       NaN       NaN  
2     39.10   23.4244       NaN       NaN  
3     38.97   23.4782       NaN       NaN  
4     39.09   23.3950       NaN       NaN  

[5 rows x 28 columns]

In [ ]:
test.shape

(16596, 28)

In [ ]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16596 entries, 0 to 16595
Data columns (total 28 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   id        16596 non-null  int64  
 1   cycle     16596 non-null  int64  
 2   op1       16596 non-null  float64
 3   op2       16596 non-null  float64
 4   op3       16596 non-null  int64  
 5   sensor1   16596 non-null  float64
 6   sensor2   16596 non-null  float64
 7   sensor3   16596 non-null  float64
 8   sensor4   16596 non-null  float64
 9   sensor5   16596 non-null  float64
 10  sensor6   16596 non-null  float64
 11  sensor7   16596 non-null  float64
 12  sensor8   16596 non-null  float64
 13  sensor9   16596 non-null  float64
 14  sensor10  16596 non-null  float64
 15  sensor11  16596 non-null  float64
 16  sensor12  16596 non-null  float64
 17  sensor13  16596 non-null  float64
 18  sensor14  16596 non-null  float64
 19  sensor15  16596 non-null  float64
 20  sensor16  16596 non-null  fl

In [ ]:
rul = pd.DataFrame(test.groupby('id')['cycle'].max()).reset_index()
rul.columns = ['id', 'max']
rul

id  max
0     1  233
1     2  124
2     3  234
3     4   68
4     5  138
..  ...  ...
95   96  358
96   97   95
97   98  182
98   99  289
99  100  247

[100 rows x 2 columns]

In [ ]:
test_results['rul_failed']=test_results['rul']+rul['max']
test_results


rul   id  rul_failed
0    44    1         277
1    51    2         175
2    27    3         261
3   120    4         188
4   101    5         239
..  ...  ...         ...
95  113   96         471
96  123   97         218
97   17   98         199
98    8   99         297
99   28  100         275

[100 rows x 3 columns]

In [ ]:
test_results.drop(["rul"],axis=1,inplace=True)

In [ ]:
test=test.merge(test_results,on=['id'],how='left')
test

id  cycle     op1     op2  op3  sensor1  sensor2  sensor3  sensor4  \
0        1      1 -0.0017 -0.0004  100   518.67   641.94  1581.93  1396.93   
1        1      2  0.0006 -0.0002  100   518.67   642.02  1584.86  1398.90   
2        1      3  0.0014 -0.0003  100   518.67   641.68  1581.78  1391.92   
3        1      4  0.0027  0.0001  100   518.67   642.20  1584.53  1395.34   
4        1      5 -0.0001  0.0001  100   518.67   642.46  1589.03  1395.86   
...    ...    ...     ...     ...  ...      ...      ...      ...      ...   
16591  100    243  0.0011 -0.0003  100   518.67   643.04  1594.99  1411.28   
16592  100    244 -0.0024  0.0002  100   518.67   642.47  1591.27  1417.64   
16593  100    245 -0.0053  0.0002  100   518.67   642.70  1593.81  1412.70   
16594  100    246 -0.0006  0.0001  100   518.67   642.19  1595.63  1406.58   
16595  100    247  0.0023  0.0004  100   518.67   643.19  1592.54  1407.20   

       sensor5  ...  sensor15  sensor16  sensor17  sensor18  sensor19  \
0        14.62  ...    8.3760      0.03       391      2388       100   
1        14.62  ...    8.4062      0.03       391      2388       100   
2        14.62  ...    8.3553      0.03       391      2388       100   
3        14.62  ...    8.3709      0.03       392      2388       100   
4        14.62  ...    8.4146      0.03       391      2388       100   
...        ...  ...       ...       ...       ...       ...       ...   
16591    14.62  ...    8.2939      0.03       395      2388       100   
16592    14.62  ...    8.3247      0.03       394      2388       100   
16593    14.62  ...    8.3264      0.03       394      2388       100   
16594    14.62  ...    8.2908      0.03       395      2388       100   
16595    14.62  ...    8.3191      0.03       392      2388       100   

       sensor20  sensor21  sensor22  sensor23  rul_failed  
0         39.07   23.4468       NaN       NaN         277  
1         39.04   23.4807       NaN       NaN         277  
2         39.10   23.4244       NaN       NaN         277  
3         38.97   23.4782       NaN       NaN         277  
4         39.09   23.3950       NaN       NaN         277  
...         ...       ...       ...       ...         ...  
16591     39.40   23.4949       NaN       NaN         275  
16592     39.42   23.6011       NaN       NaN         275  
16593     39.43   23.5482       NaN       NaN         275  
16594     39.40   23.6687       NaN       NaN         275  
16595     39.41   23.6536       NaN       NaN         275  

[16596 rows x 29 columns]

In [ ]:
test["RUL"]=test["rul_failed"]-test["cycle"]
test

id  cycle     op1     op2  op3  sensor1  sensor2  sensor3  sensor4  \
0        1      1 -0.0017 -0.0004  100   518.67   641.94  1581.93  1396.93   
1        1      2  0.0006 -0.0002  100   518.67   642.02  1584.86  1398.90   
2        1      3  0.0014 -0.0003  100   518.67   641.68  1581.78  1391.92   
3        1      4  0.0027  0.0001  100   518.67   642.20  1584.53  1395.34   
4        1      5 -0.0001  0.0001  100   518.67   642.46  1589.03  1395.86   
...    ...    ...     ...     ...  ...      ...      ...      ...      ...   
16591  100    243  0.0011 -0.0003  100   518.67   643.04  1594.99  1411.28   
16592  100    244 -0.0024  0.0002  100   518.67   642.47  1591.27  1417.64   
16593  100    245 -0.0053  0.0002  100   518.67   642.70  1593.81  1412.70   
16594  100    246 -0.0006  0.0001  100   518.67   642.19  1595.63  1406.58   
16595  100    247  0.0023  0.0004  100   518.67   643.19  1592.54  1407.20   

       sensor5  ...  sensor16  sensor17  sensor18  sensor19  sensor20  \
0        14.62  ...      0.03       391      2388       100     39.07   
1        14.62  ...      0.03       391      2388       100     39.04   
2        14.62  ...      0.03       391      2388       100     39.10   
3        14.62  ...      0.03       392      2388       100     38.97   
4        14.62  ...      0.03       391      2388       100     39.09   
...        ...  ...       ...       ...       ...       ...       ...   
16591    14.62  ...      0.03       395      2388       100     39.40   
16592    14.62  ...      0.03       394      2388       100     39.42   
16593    14.62  ...      0.03       394      2388       100     39.43   
16594    14.62  ...      0.03       395      2388       100     39.40   
16595    14.62  ...      0.03       392      2388       100     39.41   

       sensor21  sensor22  sensor23  rul_failed  RUL  
0       23.4468       NaN       NaN         277  276  
1       23.4807       NaN       NaN         277  275  
2       23.4244       NaN       NaN         277  274  
3       23.4782       NaN       NaN         277  273  
4       23.3950       NaN       NaN         277  272  
...         ...       ...       ...         ...  ...  
16591   23.4949       NaN       NaN         275   32  
16592   23.6011       NaN       NaN         275   31  
16593   23.5482       NaN       NaN         275   30  
16594   23.6687       NaN       NaN         275   29  
16595   23.6536       NaN       NaN         275   28  

[16596 rows x 30 columns]

In [ ]:
test

id  cycle     op1     op2  op3  sensor1  sensor2  sensor3  sensor4  \
0        1      1 -0.0017 -0.0004  100   518.67   641.94  1581.93  1396.93   
1        1      2  0.0006 -0.0002  100   518.67   642.02  1584.86  1398.90   
2        1      3  0.0014 -0.0003  100   518.67   641.68  1581.78  1391.92   
3        1      4  0.0027  0.0001  100   518.67   642.20  1584.53  1395.34   
4        1      5 -0.0001  0.0001  100   518.67   642.46  1589.03  1395.86   
...    ...    ...     ...     ...  ...      ...      ...      ...      ...   
16591  100    243  0.0011 -0.0003  100   518.67   643.04  1594.99  1411.28   
16592  100    244 -0.0024  0.0002  100   518.67   642.47  1591.27  1417.64   
16593  100    245 -0.0053  0.0002  100   518.67   642.70  1593.81  1412.70   
16594  100    246 -0.0006  0.0001  100   518.67   642.19  1595.63  1406.58   
16595  100    247  0.0023  0.0004  100   518.67   643.19  1592.54  1407.20   

       sensor5  ...  sensor16  sensor17  sensor18  sensor19  sensor20  \
0        14.62  ...      0.03       391      2388       100     39.07   
1        14.62  ...      0.03       391      2388       100     39.04   
2        14.62  ...      0.03       391      2388       100     39.10   
3        14.62  ...      0.03       392      2388       100     38.97   
4        14.62  ...      0.03       391      2388       100     39.09   
...        ...  ...       ...       ...       ...       ...       ...   
16591    14.62  ...      0.03       395      2388       100     39.40   
16592    14.62  ...      0.03       394      2388       100     39.42   
16593    14.62  ...      0.03       394      2388       100     39.43   
16594    14.62  ...      0.03       395      2388       100     39.40   
16595    14.62  ...      0.03       392      2388       100     39.41   

       sensor21  sensor22  sensor23  rul_failed  RUL  
0       23.4468       NaN       NaN         277  276  
1       23.4807       NaN       NaN         277  275  
2       23.4244       NaN       NaN         277  274  
3       23.4782       NaN       NaN         277  273  
4       23.3950       NaN       NaN         277  272  
...         ...       ...       ...         ...  ...  
16591   23.4949       NaN       NaN         275   32  
16592   23.6011       NaN       NaN         275   31  
16593   23.5482       NaN       NaN         275   30  
16594   23.6687       NaN       NaN         275   29  
16595   23.6536       NaN       NaN         275   28  

[16596 rows x 30 columns]

In [ ]:
df_test = test.drop(['sensor22','sensor23'], axis = 1)

In [ ]:
df_test.drop(["id","cycle","op3","sensor1","sensor5","sensor6","sensor10","sensor16","sensor18","sensor19"],axis=1,inplace=True)

In [ ]:
test_df = df_test.copy()

In [ ]:
testX = df_test.drop(['RUL'],axis = 1)
testy = df_test['RUL']

In [ ]:
pred1 = lr.predict(testX)
pred2 = rfr.predict(testX)

In [ ]:
rmse1 = mean_squared_error(testy,pred1,squared = False)
rmse1

63.52400021001272

In [ ]:
rmse2 = mean_squared_error(testy,pred2,squared = False)
rmse2

59.00035793642941

In [ ]:
df2 = pd.DataFrame({'actual':testy,'linaer reg':pred1,'random forest':pred2})
df2

actual  linaer reg  random forest
0         276  235.695874     228.681299
1         275  241.188644     225.926426
2         274  226.044551     224.150738
3         273  209.101396     225.597418
4         272  246.377685     228.921229
...       ...         ...            ...
16591      32   66.033056      86.359056
16592      31   80.126806      85.090272
16593      30   90.717862      82.295365
16594      29   73.043250      82.773218
16595      28   83.268278      80.982544

[16596 rows x 3 columns]

from predicting the RUL for maintenance it is clear that the regression models aren't showing much accuarcy. so as another method we are trying to do the same problem as a classification problem.

### Maintenance Prediction as a classification problem

In [ ]:
df_train

id  cycle     op1     op2  op3  sensor1  sensor2  sensor3  sensor4  \
0        1      1 -0.0005  0.0004  100   518.67   642.36  1583.23  1396.84   
1        1      2  0.0008 -0.0003  100   518.67   642.50  1584.69  1396.89   
2        1      3 -0.0014 -0.0002  100   518.67   642.18  1582.35  1405.61   
3        1      4 -0.0020  0.0001  100   518.67   642.92  1585.61  1392.27   
4        1      5  0.0016  0.0000  100   518.67   641.68  1588.63  1397.65   
...    ...    ...     ...     ...  ...      ...      ...      ...      ...   
24715  100    148 -0.0016 -0.0003  100   518.67   643.78  1596.01  1424.11   
24716  100    149  0.0034 -0.0003  100   518.67   643.29  1596.38  1429.14   
24717  100    150 -0.0016  0.0004  100   518.67   643.84  1604.53  1431.41   
24718  100    151 -0.0023  0.0004  100   518.67   643.94  1597.56  1426.57   
24719  100    152  0.0000  0.0003  100   518.67   643.64  1599.04  1436.06   

       sensor5  ...  sensor14  sensor15  sensor16  sensor17  sensor18  \
0        14.62  ...   8145.32    8.4246      0.03       391      2388   
1        14.62  ...   8152.85    8.4403      0.03       392      2388   
2        14.62  ...   8150.17    8.3901      0.03       391      2388   
3        14.62  ...   8146.56    8.3878      0.03       392      2388   
4        14.62  ...   8147.80    8.3869      0.03       392      2388   
...        ...  ...       ...       ...       ...       ...       ...   
24715    14.62  ...   8138.08    8.5036      0.03       394      2388   
24716    14.62  ...   8144.36    8.5174      0.03       395      2388   
24717    14.62  ...   8135.95    8.5223      0.03       396      2388   
24718    14.62  ...   8141.24    8.5148      0.03       395      2388   
24719    14.62  ...   8136.98    8.5150      0.03       396      2388   

       sensor19  sensor20  sensor21  rul_failed  RUL  
0           100     39.11   23.3537         303  302  
1           100     38.99   23.4491         303  301  
2           100     38.85   23.3669         303  300  
3           100     38.96   23.2951         303  299  
4           100     39.14   23.4583         303  298  
...         ...       ...       ...         ...  ...  
24715       100     38.44   22.9631         180   32  
24716       100     38.50   22.9746         180   31  
24717       100     38.39   23.0682         180   30  
24718       100     38.31   23.0753         180   29  
24719       100     38.56   23.0847         180   28  

[24720 rows x 28 columns]

In [ ]:
cycle=30
df_train['label'] = df_train['RUL'].apply(lambda x: 1 if x <= cycle else 0)


In [ ]:
op_set=["op"+str(i) for i in range(1,4)]
sensor=["sensor"+str(i) for i in range(1,22)]


In [ ]:
df_train.label.unique()

array([0, 1])

In [ ]:
df_train['label'].value_counts()

0    24429
1      291
Name: label, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X=df_train.drop(["id","cycle","op3","sensor1","sensor5","sensor6","sensor10","sensor16","sensor18","sensor19","RUL",'label'],axis=1)
y=df_train['label']

In [ ]:
from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler(random_state=42)
X, y = ros.fit_resample(X, y)

# Create a new dataframe with resampled data
df_train= pd.concat([pd.DataFrame(X), pd.Series(y, name='label')], axis=1)


In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X,y, test_size = 0.20, random_state = 42)


In [ ]:
df_train.shape

(48858, 18)

In [ ]:
from sklearn.linear_model import LogisticRegression
lr= LogisticRegression()
lr.fit(X_train,Y_train)
train_pred = lr.predict(X_train)
test_pred = lr.predict(X_test)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
confusion_matrix(Y_test,test_pred)

array([[4403,  390],
       [ 170, 4809]])

In [ ]:
accuracy_score(Y_test,test_pred)

0.9426934097421203

In [ ]:
confusion_matrix(Y_train,train_pred)

array([[18000,  1636],
       [  675, 18775]])

In [ ]:
accuracy_score(Y_train,train_pred)

0.9408739702195159

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(X_train,Y_train)
dtc_train_pred = dtc.predict(X_train)
dtc_test_pred = dtc.predict(X_test)

In [ ]:
confusion_matrix(Y_train,dtc_train_pred)

array([[19636,     0],
       [    0, 19450]])

In [ ]:
accuracy_score(Y_train,dtc_train_pred)

1.0

In [ ]:
confusion_matrix(Y_test,dtc_test_pred)

array([[4774,   19],
       [   0, 4979]])

In [ ]:
accuracy_score(Y_test,dtc_test_pred)

0.9980556692591076

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc.fit(X_train,Y_train)
rfc_train_pred = rfc.predict(X_train)
rfc_test_pred = rfc.predict(X_test)

In [ ]:
confusion_matrix(Y_train,rfc_train_pred)

array([[19636,     0],
       [    0, 19450]])

In [ ]:
accuracy_score(Y_train,rfc_train_pred)

1.0

In [ ]:
confusion_matrix(Y_test,rfc_test_pred)

array([[4780,   13],
       [   0, 4979]])

In [ ]:
accuracy_score(Y_test,rfc_test_pred)

0.998669668440442

from doing the classification models like linear regression, decision tree and random forest we can conlcude that for logistic regression model both training and testing data show similar accuarcy and we choose that mode

#### validating the models using test data.

In [ ]:
df_test

op1     op2  sensor2  sensor3  sensor4  sensor7  sensor8  sensor9  \
0     -0.0017 -0.0004   641.94  1581.93  1396.93   554.56  2387.93  9048.65   
1      0.0006 -0.0002   642.02  1584.86  1398.90   554.10  2387.94  9046.53   
2      0.0014 -0.0003   641.68  1581.78  1391.92   554.41  2387.97  9054.92   
3      0.0027  0.0001   642.20  1584.53  1395.34   554.58  2387.94  9055.04   
4     -0.0001  0.0001   642.46  1589.03  1395.86   554.16  2388.01  9048.59   
...       ...     ...      ...      ...      ...      ...      ...      ...   
16591  0.0011 -0.0003   643.04  1594.99  1411.28   561.21  2388.24  9088.31   
16592 -0.0024  0.0002   642.47  1591.27  1417.64   561.02  2388.29  9085.35   
16593 -0.0053  0.0002   642.70  1593.81  1412.70   561.16  2388.23  9084.29   
16594 -0.0006  0.0001   642.19  1595.63  1406.58   562.66  2388.24  9092.52   
16595  0.0023  0.0004   643.19  1592.54  1407.20   562.32  2388.30  9094.27   

       sensor11  sensor12  sensor13  sensor14  sensor15  sensor17  sensor20  \
0         47.09    521.89   2387.94   8133.48    8.3760       391     39.07   
1         47.08    521.85   2388.01   8137.44    8.4062       391     39.04   
2         47.15    522.10   2387.94   8138.25    8.3553       391     39.10   
3         47.26    522.45   2387.96   8137.07    8.3709       392     38.97   
4         46.94    521.91   2387.97   8134.20    8.4146       391     39.09   
...         ...       ...       ...       ...       ...       ...       ...   
16591     47.61    529.23   2388.24   8162.24    8.2939       395     39.40   
16592     47.75    529.27   2388.26   8163.24    8.3247       394     39.42   
16593     47.60    529.48   2388.28   8162.12    8.3264       394     39.43   
16594     47.69    529.39   2388.33   8164.20    8.2908       395     39.40   
16595     47.71    529.59   2388.29   8169.24    8.3191       392     39.41   

       sensor21  rul_failed  RUL  
0       23.4468         277  276  
1       23.4807         277  275  
2       23.4244         277  274  
3       23.4782         277  273  
4       23.3950         277  272  
...         ...         ...  ...  
16591   23.4949         275   32  
16592   23.6011         275   31  
16593   23.5482         275   30  
16594   23.6687         275   29  
16595   23.6536         275   28  

[16596 rows x 18 columns]

In [ ]:
df_test.shape

(16596, 18)

In [ ]:
cycle=30
df_test['label'] = df_test['RUL'].apply(lambda x: 1 if x <= cycle else 0)



In [ ]:
df_test

op1     op2  sensor2  sensor3  sensor4  sensor7  sensor8  sensor9  \
0     -0.0017 -0.0004   641.94  1581.93  1396.93   554.56  2387.93  9048.65   
1      0.0006 -0.0002   642.02  1584.86  1398.90   554.10  2387.94  9046.53   
2      0.0014 -0.0003   641.68  1581.78  1391.92   554.41  2387.97  9054.92   
3      0.0027  0.0001   642.20  1584.53  1395.34   554.58  2387.94  9055.04   
4     -0.0001  0.0001   642.46  1589.03  1395.86   554.16  2388.01  9048.59   
...       ...     ...      ...      ...      ...      ...      ...      ...   
16591  0.0011 -0.0003   643.04  1594.99  1411.28   561.21  2388.24  9088.31   
16592 -0.0024  0.0002   642.47  1591.27  1417.64   561.02  2388.29  9085.35   
16593 -0.0053  0.0002   642.70  1593.81  1412.70   561.16  2388.23  9084.29   
16594 -0.0006  0.0001   642.19  1595.63  1406.58   562.66  2388.24  9092.52   
16595  0.0023  0.0004   643.19  1592.54  1407.20   562.32  2388.30  9094.27   

       sensor11  sensor12  sensor13  sensor14  sensor15  sensor17  sensor20  \
0         47.09    521.89   2387.94   8133.48    8.3760       391     39.07   
1         47.08    521.85   2388.01   8137.44    8.4062       391     39.04   
2         47.15    522.10   2387.94   8138.25    8.3553       391     39.10   
3         47.26    522.45   2387.96   8137.07    8.3709       392     38.97   
4         46.94    521.91   2387.97   8134.20    8.4146       391     39.09   
...         ...       ...       ...       ...       ...       ...       ...   
16591     47.61    529.23   2388.24   8162.24    8.2939       395     39.40   
16592     47.75    529.27   2388.26   8163.24    8.3247       394     39.42   
16593     47.60    529.48   2388.28   8162.12    8.3264       394     39.43   
16594     47.69    529.39   2388.33   8164.20    8.2908       395     39.40   
16595     47.71    529.59   2388.29   8169.24    8.3191       392     39.41   

       sensor21  rul_failed  RUL  label  
0       23.4468         277  276      0  
1       23.4807         277  275      0  
2       23.4244         277  274      0  
3       23.4782         277  273      0  
4       23.3950         277  272      0  
...         ...         ...  ...    ...  
16591   23.4949         275   32      0  
16592   23.6011         275   31      0  
16593   23.5482         275   30      1  
16594   23.6687         275   29      1  
16595   23.6536         275   28      1  

[16596 rows x 19 columns]

In [ ]:
test_X = df_test.drop(['label','RUL'],axis = 1)
test_y = df_test['label']

In [ ]:
from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler(random_state=42)
test_X, test_y = ros.fit_resample(test_X, test_y)

# Create a new dataframe with resampled data
df_test= pd.concat([pd.DataFrame(test_X), pd.Series(test_y, name='label')], axis=1)


In [ ]:
pred = lr.predict(test_X)

In [ ]:
pred

array([0, 0, 0, ..., 1, 1, 1])

In [ ]:
confusion_matrix(test_y,pred)

array([[16123,   182],
       [ 2612, 13693]])

In [ ]:
accuracy_score(test_y,pred)

0.9143207605029132

In [ ]:
dff = pd.DataFrame({'actual':test_y,'predicted':pred})
dff = dff[dff['actual']==1]
dff

actual  predicted
587         1          1
588         1          1
589         1          1
590         1          1
3347        1          1
...       ...        ...
32605       1          1
32606       1          1
32607       1          1
32608       1          1
32609       1          1

[16305 rows x 2 columns]

by doing prediction using classification more accuracy is obtained. even though we didn't the exact RUL we can predict if or whether the machine need maintenace within the threshold day we set.